add yuque(https://www.yuque.com) loader
langflow-ai/langflow pull request #1874
Opened 2024-05-10 15:24 UTC by liujichengs

yuque(https://www.yuque.com)  is an online document library for collaboration between multiple teams.Contains a lot of knowledge and provides rich clients for users to use。The establishment of Yuque loader can provide developers with a more convenient way to obtain data, improve efficiency and lower the threshold of use.

2024-05-23 19:15 UTC, ogabrielluiz requested changes
Thanks, @liujichengs !

2024-05-23 19:15 UTC, ogabrielluiz commented on src/backend/base/langflow/helpers/YuQueTool.py
Hey @liujichengs 
Great implementation. Sorry for the delayed response. 

Could you move this to `langflow/base/loaders/yuque.py`?

2024-05-24 06:09 UTC, liujichengs commented on src/backend/base/langflow/helpers/YuQueTool.py
hi,  @ogabrielluiz  I have modified it, thank you for your reply

2024-07-05 16:35 UTC, ogabrielluiz approved these changes

2024-10-04 14:34 UTC, anovazzi1 commented
Thank you so much for your effort and contribution! While we truly appreciate the work you've put into this, we are currently focusing on enhancing the Langflow Store, where third-party integrations will be hosted. I encourage you to upload your components to the Langflow Store for better visibility and use. For now, we’ll be closing this PR, but we’re deeply grateful for your support and look forward to your future contributions!

2024-10-04 14:34 UTC, closed without merging