Feature: Updated Chat History for Astra DB
langflow-ai/langflow pull request #1895
Opened 2024-05-14 20:59 UTC by erichare

This Pull Request adds Chat History based on session IDs for Astra DB.

2024-05-15 14:40 UTC, ogabrielluiz approved these changes
LGTM

2024-05-21 09:50 UTC, nicoloboschi requested changes

2024-05-21 09:50 UTC, nicoloboschi commented on src/backend/base/langflow/components/memories/AstraDBMessageReader.py
> +from langchain_community.chat_message_histories.astradb import AstraDBChatMessageHistory
we should use the new package

2024-05-21 09:51 UTC, nicoloboschi commented on src/backend/base/langflow/components/memories/AstraDBMessageWriter.py
> +            "namespace": {
"advanced": True, like the vector store

2024-05-21 09:51 UTC, nicoloboschi commented on src/backend/base/langflow/components/memories/AstraDBMessageReader.py
> +            "namespace": {
"advanced": True, like the vector store

2024-05-21 14:49 UTC, erichare commented on src/backend/base/langflow/components/memories/AstraDBMessageReader.py
> +from langchain_community.chat_message_histories.astradb import AstraDBChatMessageHistory
Updated, good call

2024-05-21 14:49 UTC, erichare commented on src/backend/base/langflow/components/memories/AstraDBMessageWriter.py
> +            "namespace": {
Done.

2024-05-21 14:49 UTC, erichare commented on src/backend/base/langflow/components/memories/AstraDBMessageReader.py
> +            "namespace": {
Done.

2024-05-21 15:26 UTC, nicoloboschi approved these changes
LGTM, great work!

2024-05-22 16:52 UTC, erichare commented
@ogabrielluiz anything holding back the merge? I see a build issue but i think thats unrelated, correct me if im wrong?

I'd be happy to add a test or some kind of validation, just might need a little guidance there - maybe there's something for Zep available? Just let me know if so!

2024-05-23 13:13 UTC, ogabrielluiz commented
@erichare should be good to go. It is still a bit hard to add automated tests for these integration components.

2024-05-23 13:13 UTC, merged