Astra Assistants Support
langflow-ai/langflow pull request #2041
Opened 2024-06-01 04:33 UTC by phact

Added a few components to support [astra-assistants](https://github.com/datastax/astra-assistants-api/tree/main), an open source implementation of OpenAI's assistants API that supports different LLM and embedding providers.

2024-06-03 21:40 UTC, ogabrielluiz commented
Hey @phact !! 

How are you? 

This looks so cool!

2024-06-03 23:53 UTC, phact commented
Hey @ogabrielluiz , doing great :) 

Excited about this first stab at Assistants support. This is my first component contribution. What steps do you recommend to get it ready to merge? I plan to continue improving and maintaining Assistants support in langflow going forward if that works for you and he team.

2024-06-06 12:23 UTC, ogabrielluiz commented on src/backend/base/langflow/config.yaml
You don't need this. We are removing this config.

2024-06-06 12:24 UTC, ogabrielluiz requested changes
Hey @phact 

You might want to add `build_config` to the components so the Fields have better names and information on how to use them.

2024-06-17 14:48 UTC, phact commented
Hi @ogabrielluiz any additional feedback now that your suggestions were addressed?

Thanks!!!

2024-06-25 14:09 UTC, phact commented
Hey @ogabrielluiz just checking in. Congrats on the v1 launch!

2024-07-10 16:37 UTC, phact commented
@ogabrielluiz checking in on this

2024-07-10 17:39 UTC, ogabrielluiz commented
Thank you, Seb! We'll take a stance on this PR this week. I'll change the base to `main` and pick a category for them.

2024-07-22 17:24 UTC, ogabrielluiz approved these changes

2024-07-22 17:26 UTC, merged