cache components loaded from components_path when the /all is called
langflow-ai/langflow pull request #2197
Opened 2024-06-17 12:57 UTC by zzzming

api/v1/all can take seconds to build components from the component folder. This is an improvement to cache the build results from the components_path folder. 

Since it's permanently cached, I assume the content from the components_path folder only been loaded once.

2024-06-17 13:10 UTC, ogabrielluiz commented
Hey @zzzming 

Could you check the two_edges branch? I have a solution there on this topic.

2024-06-17 13:35 UTC, zzzming commented
> Hey @zzzming
> 
> Could you check the two_edges branch? I have a solution there on this topic.

@ogabrielluiz Nice! Yours are much better. Is the initial call `aget_all_types_dict` still taking a few seconds? Can we add it to setup.py to shorten the first call's time?

2024-06-17 21:15 UTC, ogabrielluiz commented
> > Hey @zzzming
> > Could you check the two_edges branch? I have a solution there on this topic.
> 
> @ogabrielluiz Nice! Yours are much better. Is the initial call `aget_all_types_dict` still taking a few seconds? Can we add it to setup.py to shorten the first call's time?

It still takes a while because it has to run at least once. We need a better loading setup but requires a pretty big refactor. 
There's also some optimization opportunity yet in the loading process that we can implement some time soon like making it more async

2024-06-18 01:52 UTC, zzzming commented
> > > Hey @zzzming
> > > Could you check the two_edges branch? I have a solution there on this topic.
> > 
> > 
> > @ogabrielluiz Nice! Yours are much better. Is the initial call `aget_all_types_dict` still taking a few seconds? Can we add it to setup.py to shorten the first call's time?
> 
> It still takes a while because it has to run at least once. We need a better loading setup but requires a pretty big refactor. There's also some optimization opportunity yet in the loading process that we can implement some time soon like making it more async

@ogabrielluiz can we do something like create_or_update_starter_project() that is called by main.py? We can make this as async so that aget_all_types_dict() won't take much the bootstrap time. Do you think that makes sense?

2024-06-18 10:37 UTC, nicoloboschi requested changes
Why don't we just do this at the startup once in the lifespan hook? 

components path is static and won't change without restarting the service 

also the current proposed change doesn't ensure the components are loaded once

2024-06-19 14:32 UTC, zzzming commented
Close this PR
We will make a change if necessary after two_edges is merged in

2024-06-19 14:32 UTC, closed without merging