Refactor DirectoryComponent to filter file paths by types
langflow-ai/langflow pull request #2391
Opened 2024-06-27 03:24 UTC by carlosrcoelho

The "Type" option of the component has been adjusted to ensure the file type is selected correctly.

2024-06-27 11:32 UTC, ogabrielluiz requested changes
Hey @carlosrcoelho 

Thanks! 

I think this component was not correct from the start.

2024-06-27 11:32 UTC, ogabrielluiz commented on src/backend/base/langflow/components/data/Directory.py
The component is wrong I think. The `types` field should be a list field. That's why the self.types requires a call to `split` but shouldn't.

2024-07-04 18:42 UTC, ogabrielluiz approved these changes

2024-07-05 15:17 UTC, carlosrcoelho commented on src/backend/base/langflow/components/data/Directory.py
@ogabrielluiz Please verify the corrections applied.

2024-07-05 15:17 UTC, merged