Feature: Add multiselect ui-component and merge refs hook
langflow-ai/langflow pull request #2405
Opened 2024-06-27 15:23 UTC by 596050

New MultiSelect Component

I've been trying out some new langflow components I'd like to add to the codebase but they need something like a multi select ui-component which appears to be unavailable. Currently no tests because there appear to be end-to-end tests only which requires the ui-component to be in a langflow component, currently no langflow components have this ui-component in it. Would be great to discuss.

Usage:

```jsx
<MultiSelect
  disabled={disabled}
  options={[
    { value: "option_1", label: "This is an extra extra extra long label to shsow responsiveness of the component" },
    { value: "option_2", label: "Option A" },
    { value: "option_3", label: "Option B" },
    { value: "option_4", label: "Option C" },
    { value: "option_5", label: "Option D" },
  ]}
  value={data?.node?.template?.[name]?.value || []}
  id={"multiselect-" + name}
  onValueChange={handleOnNewValue}
/>
```

User experience:
https://github.com/langflow-ai/langflow/assets/19141517/cffd9d64-414a-4ac8-8008-5a8ad2797546

Also adds a useMergeRefs custom hook

2024-06-27 17:19 UTC, ogabrielluiz commented
Wow! That's really awesome and really needed. 

Thank you so much @596050

2024-06-27 17:20 UTC, ogabrielluiz commented
I can add support for it on the Component in no time.

2024-07-02 13:52 UTC, lucaseduoli commented
Hello!

I loved this component. Can you implement it on the ParameterComponent and the TableNodeCellRenderer please?
The conditions to show the component are going to be:

- Type is "str"
- template[name].options exist
- template[name].list is true

 We're going to implement the backend components to use that as soon as possible.

2024-07-02 13:52 UTC, lucaseduoli requested changes
Hello!

I loved this component. Can you implement it on the ParameterComponent and the TableNodeCellRenderer please?
The conditions to show the component are going to be:

Type is "str"
template[name].options exist
template[name].list is true
We're going to implement the backend components to use that as soon as possible.

2024-07-05 16:16 UTC, ogabrielluiz requested changes
Hey @596050 

Just this fix and we can merge it.

2024-07-05 16:16 UTC, ogabrielluiz commented on src/backend/base/langflow/inputs/inputs.py
> +class MultiselectInput(BaseInputMixin, MultiselectMixin, MetadataTraceMixin):
```suggestion
class MultiselectInput(BaseInputMixin, ListableMixin, DropDownMixin, MetadataTraceMixin):
    field_type: Optional[SerializableFieldTypes] = FieldTypes.TEXT
```

I think this should be enough to create this type.

2024-07-11 16:14 UTC, merged