fix(get-python-api-code):fixing errors in a file uploading flow, as in issue #2799
langflow-ai/langflow pull request #2815
Opened 2024-07-18 23:27 UTC by vertgo

fixed the code to allow a return value of 201
properly parse the components argument
handle the case of having no endpoint name to default to flow_id
changing the tweak value of path instead of file_path (correct for the file component)

2024-07-23 00:22 UTC, ogabrielluiz requested changes

2024-08-08 13:52 UTC, ogabrielluiz approved these changes

2024-08-09 22:41 UTC, vertgo reviewed
this looks good to me

2024-08-09 22:42 UTC, vertgo commented on src/backend/base/langflow/load/utils.py
> +                    tweaks[component] = {"path": response["file_path"]}
if some components use file_path and others use path then we can set them both in tweaks

2024-08-09 22:53 UTC, merged