feat: Add GitLoader Component with advanced filtering options
langflow-ai/langflow pull request #2850
Opened 2024-07-20 00:59 UTC by danielgines

This commit introduces the GitLoaderComponent, enabling users to load files from a Git repository with advanced filtering options.

GitLoader Component:

- Implementation of the GitLoaderComponent to load files from a Git repository using the `langchain_community.document_loaders.git.GitLoader` module.
- Advanced filtering option using `file_filter` to include or exclude specific files based on their extensions or other criteria.

Examples of `file_filter` usage:
- Include only .py files: `lambda file_path: file_path.endswith('.py')`
- Exclude .py files: `lambda file_path: not file_path.endswith('.py')`

This component ensures a flexible and customizable approach for loading documents from Git repositories, enhancing the user experience with advanced filtering capabilities.

Features:

- Support for loading documents from Git repositories.
- Advanced file filtering options to include or exclude specific files.

2024-07-25 02:01 UTC, ogabrielluiz requested changes

2024-07-26 21:54 UTC, danielgines commented on src/backend/base/langflow/components/documentloaders/GitLoader.py
> +            file_filter = eval(self.file_filter)
Sure, sounds great! I'll go ahead and implement it.

2024-07-29 18:51 UTC, danielgines reviewed
@ogabrielluiz 

I applied the suggestion you recommended and took the opportunity to make a small improvement to the agent based on my use case. I look forward to your feedback.

2024-07-30 01:50 UTC, ogabrielluiz approved these changes
That's a lot nicer. 

Thanks for all the help, @danielgines

2024-07-30 02:00 UTC, merged