astra-assistants
langflow-ai/langflow pull request #2881
Opened 2024-07-22 20:34 UTC by phact

Update to use Components with inputs and outputs for compatibility with Text Output and Chat Output components.

Apologies this didn't make it into the last PR.

2024-07-23 14:34 UTC, anovazzi1 requested changes
Thanks for the pull request. I've noticed some minor bugs in the code. Could you please review and fix them?

2024-07-23 14:34 UTC, anovazzi1 commented on src/frontend/src/components/textAreaComponent/index.tsx
broken field:
please update:
- fix the ui in the node
- update the field in the node modal
- update the field in the tweaks
![image](https://github.com/user-attachments/assets/ec3aba5a-7dd4-41c3-a30d-67633e4a8e9b)
![image](https://github.com/user-attachments/assets/62de4ffa-6449-4a20-8440-8ddbcd57930b)
![image](https://github.com/user-attachments/assets/0a76d04c-0a10-41cf-a7e5-1e68daa3fee0)

2024-07-23 14:34 UTC, anovazzi1 commented on src/backend/base/langflow/components/astra_assistants/list_assistants.py
fix broken component:

![image](https://github.com/user-attachments/assets/01462ebf-c6ab-4c26-a3f5-0a701fa43704)

2024-07-23 15:10 UTC, ogabrielluiz commented on src/backend/base/langflow/components/astra_assistants/list_assistants.py
This is correct.

2024-07-23 20:00 UTC, phact commented on src/frontend/src/components/textAreaComponent/index.tsx
Fixed!

2024-07-25 22:12 UTC, anovazzi1 approved these changes
LGTM

2024-07-28 22:15 UTC, anovazzi1 approved these changes
LGTM

2024-07-29 17:56 UTC, merged