enhancement: Add function to check broken edges
langflow-ai/langflow pull request #2882
Opened 2024-07-22 22:40 UTC by anovazzi1

This pull request adds a new function to check for broken edges in the code. The function detects if the source or target nodes or handles no longer exist and displays an error message with the list of broken edges.

2024-07-23 14:10 UTC, ogabrielluiz commented on src/frontend/src/utils/utils.ts
> +export function BrokenEdgeMessage({
```suggestion
export function brokenEdgeMessage({
```

2024-07-23 14:10 UTC, ogabrielluiz commented on src/frontend/src/stores/flowsManagerStore.ts
> +            list: brokenEdges.map((edge) => BrokenEdgeMessage(edge)),
```suggestion
            list: brokenEdges.map((edge) => brokenEdgeMessage(edge)),
```

2024-07-23 14:11 UTC, ogabrielluiz commented on src/frontend/src/stores/flowStore.ts
> +          list: brokenEdges.map((edge) => BrokenEdgeMessage(edge)),
```suggestion
          list: brokenEdges.map((edge) => brokenEdgeMessage(edge)),
```

2024-07-23 14:11 UTC, ogabrielluiz commented on src/frontend/src/stores/flowStore.ts
> +import { BrokenEdgeMessage } from "@/utils/utils";
```suggestion
import { brokenEdgeMessage } from "@/utils/utils";
```

2024-07-23 14:50 UTC, anovazzi1 commented on src/frontend/src/utils/utils.ts
> +  return `${source} -> ${target}`;
maybe this will be too verbose? the edge is already deleted, i can't see how this change helps the user to identify which edge was deleted

2024-07-23 15:13 UTC, ogabrielluiz commented on src/frontend/src/utils/utils.ts
> +  return `${source} -> ${target}`;
They might not remember which edge was put where.

2024-07-23 15:17 UTC, ogabrielluiz commented on src/frontend/src/utils/utils.ts
> +  return `${source} -> ${target}`;
If we can give more info so that the user does not have to think when fixing the problem, we should do it.

2024-07-23 19:07 UTC, anovazzi1 commented on src/frontend/src/utils/utils.ts
> +  return `${source} -> ${target}`;
sure,I will update

2024-07-23 21:45 UTC, ogabrielluiz requested changes

2024-07-23 21:45 UTC, ogabrielluiz commented on src/frontend/src/utils/utils.ts
> +  console.log("target", target);
```suggestion
```

2024-07-24 17:01 UTC, ogabrielluiz approved these changes

2024-07-24 17:02 UTC, merged