refactor: add flow and upload flow functionality
langflow-ai/langflow pull request #3200
Opened 2024-08-05 18:00 UTC by lucaseduoli

- Adds Add Flow and Upload Flow hooks
- Uses those hooks in all of the linked components
- Adds helper upload functions
- Handles various errors relating to file uploads, making it more generic

2024-08-05 22:42 UTC, anovazzi1 requested changes
ran tests locally, failed at DragAndDrop,folders,generalBugs-shard-4

2024-08-05 22:42 UTC, anovazzi1 commented on src/frontend/src/pages/MainPage/components/componentsComponent/index.tsx
> +  const [handleFileDrop] = useFileDrop(type)!;
1 - there is no reason for the ! mark in that line
2 - why is the useFileDrop returning a list if there is only one element on it?

2024-08-05 22:43 UTC, lucaseduoli commented on src/frontend/src/components/headerComponent/components/menuBar/index.tsx
> +                uploadFlow({ position: { x: 300, y: 100 } })
the position is passed because the position is the new way of knowing if the flow is going to be pasted or created

2024-08-05 22:47 UTC, lucaseduoli commented on src/frontend/src/helpers/create-file-upload.ts
> +    window.addEventListener(
actually it does not get removed with the onChange. It needs to be removed manually

2024-08-05 22:56 UTC, anovazzi1 commented on src/frontend/src/components/headerComponent/components/menuBar/index.tsx
> +                uploadFlow({ position: { x: 300, y: 100 } })
makes sense

2024-08-05 22:57 UTC, anovazzi1 commented on src/frontend/src/helpers/create-file-upload.ts
> +    window.addEventListener(
the line 16 does not remove the input after the files are selected?

2024-08-06 16:45 UTC, lucaseduoli commented on src/frontend/src/helpers/create-file-upload.ts
> +    window.addEventListener(
we have to remove it in case the file isnt selected

2024-08-06 16:46 UTC, lucaseduoli commented on src/frontend/src/hooks/flows/use-upload-flow.ts
i think its gonna be more confusing to the user, since the flow is gonna be uploaded but not visible to him

2024-08-06 20:10 UTC, anovazzi1 approved these changes
LGTM

2024-08-06 21:52 UTC, merged