FIX: Dependency update for unstructured component
langflow-ai/langflow pull request #3552
Opened 2024-08-26 16:45 UTC by erichare

This PR makes two changes to the dependencies of the project:

1. It adds the `pdf` extra package for unstructured, for processing PDFs
2. It bumps the minimum version for `huggingface-hub` which is required for Unstructured.

2024-08-26 21:23 UTC, ogabrielluiz approved these changes
LGTM

2024-08-27 09:50 UTC, nicoloboschi requested changes
Could you explain how the new script `nltk_setup` is intended to be used ?

2024-08-27 11:52 UTC, erichare commented
> Could you explain how the new script `nltk_setup` is intended to be used ?

Hi @nicoloboschi 

the unstructured component, and specifically the pdf parsing tools, use nltk behind the scenes. But they assume that these three packages, punkt etc, are already available on the host - if they aren’t, the component will error and ask you to download them first.

so the basic idea is just that every time we deploy a release that we are sure those nltk packages are on the machine and accessible for the nltk library - does that make sense? Maybe there’s another way to go about it, I.,e, the dockerfile orchestrates it? But that’s the idea

2024-08-27 13:06 UTC, nicoloboschi commented
@erichare could we make it part of the `langflow run` script?
and at the bootstrap it verifies/download the needed files

The current format is not that helpful in fix/troubleshoot the problem

2024-08-27 14:57 UTC, erichare commented
> feat: allow drive loader to read a folder recursively #3572

@nicoloboschi when you get a chance, could you look at the latest commit? I'm not sure whether i put it exactly in the most logical place, but the utility function for downloading the resources i put in setup.py, then the run script imports that function and calls it at startup. If the packages are already available, it'll skip downloading them.

2024-08-30 03:02 UTC, zzzming approved these changes

2024-08-30 03:02 UTC, zzzming commented on src/backend/base/langflow/initial_setup/setup.py
> +                print(f"{package} ({category}) already exists.")
is there a better logging function than just print() ?
I saw logging.info() is used 11  lines above

2024-08-30 06:31 UTC, nicoloboschi approved these changes
LGTM

2024-08-30 13:48 UTC, merged