Feat:data-components-utilities
langflow-ai/langflow pull request #3776
Opened 2024-09-11 20:29 UTC by vasconceloscezar

New helper Data components were added: 

- CSV to Data
- JSON to Data
- Data Conditional Router
- Extract Key 
- Filter Data Values
- JSON to Data

2024-09-16 16:47 UTC, ogabrielluiz commented
Hey @vasconceloscezar 

These look awesome. Really useful stuff. 

Could you review the PR title to be something a bit more descriptive? 

Thanks!

2024-09-18 14:21 UTC, ogabrielluiz requested changes
This is looking good. 

What do you think about another component that turns a Message into a Data  (should be as simple as `Data(data=message.data)`

2024-09-18 22:25 UTC, vasconceloscezar commented
I changed both JSON and CSV loaders to accept File, Path or String representation. 

![image](https://github.com/user-attachments/assets/aa49f856-f1b5-4ce9-ad7f-f43b5d346de1)

And this is the new Message to Data
![image](https://github.com/user-attachments/assets/8240d07b-21ec-42c0-be05-363937205e62)

2024-09-19 13:12 UTC, ogabrielluiz approved these changes

2024-10-03 15:48 UTC, merged