Fix notes design
langflow-ai/langflow pull request #3938
Opened 2024-09-26 18:14 UTC by Yukiyukiyeah

2024-09-30 15:08 UTC, NadirJ approved these changes

2024-10-01 15:06 UTC, deon-sanchez approved these changes

2024-10-01 18:29 UTC, lucaseduoli commented
Could you maybe make the notes horizontal padding a little smaller? And perhaps make the duplicated note the same size as the old one?

2024-10-01 18:32 UTC, ogabrielluiz requested changes
https://github.com/langflow-ai/langflow/pull/3938#issuecomment-2386690122

Just pasting this here to force the changes being requests

2024-10-01 20:57 UTC, ogabrielluiz approved these changes

2024-10-02 12:45 UTC, merged