Refactor parameter render component
langflow-ai/langflow pull request #3995
Opened 2024-10-02 21:04 UTC by anovazzi1

This pull request includes several refactorings and additions to the parameter render component.

The refactorings include:

- Updating the dynamic parameter in the ParameterRenderComponent to false

- Updating the CodeAreaComponent to use CodeAreaModal for the node toolbar

- Updating the RefreshParameterComponent to use InputProps

- Updating the InputProps in parameterRenderComponent/types.ts

- Updating the parameterRenderComponent/types.ts to use handleOnNewValue instead of onChange

- Updating the TableModal to support disabled state

- Updating the parameterRenderComponent/types.ts to include TableComponentType

- Updating the parameterRenderComponent to use TableNodeComponent from the correct folder

- Updating the codeAreaComponent imports and props in parameterRenderComponent

- Updating the parameterRenderComponent/types.ts to include CodeAreaComponentType

- Removing unused imports of CodeAreaComponent in nodeToolbarComponent

- Updating the ToggleComponentType in components/index.ts

- Updating the ToggleShadComponent to handle new value changes

- Moving the InputFileComponent to parameterRenderComponent/components folder

- Adding the FileComponentType interface to parameterRenderComponent/types.ts

- Updating the InputFileComponent props in parameterRenderComponent

- Moving the PromptAreaComponent to parameterRenderComponent/components folder

- Updating the PromptAreaComponent to handle new value changes

- Moving the LinkComponent to parameterRenderComponent/components folder

- Adding the LinkComponentType interface to parameterRenderComponent/types.ts

- Updating the LinkComponent to use InputProps in parameterRenderComponent

- Moving the KeypairListComponent to parameterRenderComponent/components folder

- Adding the KeyPairListComponentType interface to parameterRenderComponent/types.ts

- Updating the KeypairListComponent to use InputProps in parameterRenderComponent

- Moving the DictComponent to parameterRenderComponent/components folder

- Updating the KeyPairListComponentType interface in parameterRenderComponent/types.ts

- Updating the KeypairListComponent to use InputProps in parameterRenderComponent

- Moving the InputListComponent to parameterRenderComponent/components folder

- Adding the StrRenderComponentType interface to parameterRenderComponent/types.ts

- Updating the InputListComponent to use InputProps in parameterRenderComponent

- Moving the IOFieldView to IOModal/components folder

- Moving the DropdownComponent to parameterRenderComponent/components folder

- Adding the DropDownComponentType interface to parameterRenderComponent/types.ts

- Updating the DropdownComponent import in StrRenderComponent

- Updating the StrRenderComponent to use baseInputProps

- Updating the StrRenderComponent to use TextAreaComponent from correct location

- Removing unused imports

- Adding the TextAreaComponentType interface to parameterRenderComponent/types.ts

- Updating the TextAreaComponent to use handleOnNewValue instead of onChange

- Updating the StrRenderComponent to use baseInputProps

- Moving the inputGlobalComponent to parameterRenderComponent/components folder

- Updating the InputGlobalComponent to use handleOnNewValue instead of onChange

- Updating the StrRenderComponent to use baseInputProps

- Moving the multiselectComponent to parameterRenderComponent/components folder

- Moving the MultiselectComponent to parameterRenderComponent/components folder

- Removing unused code in StrRenderComponent

- Updating the FloatComponent to use InputProps

The additions include:

- Adding the EmptyParameterComponent to render empty parameters

These changes improve code organization, maintainability, and functionality of the parameter render component.

2024-10-04 15:05 UTC, Cristhianzl approved these changes
lgtm

2024-10-04 20:05 UTC, lucaseduoli requested changes
LGTM, only these minor changes

2024-10-04 20:05 UTC, lucaseduoli commented on src/frontend/src/components/parameterRenderComponent/components/dictComponent/index.tsx
> +      handleOnNewValue({ value: {} });
I think skipSnapshot is necessary here as well.

2024-10-04 20:05 UTC, lucaseduoli commented on src/frontend/src/components/parameterRenderComponent/components/keypairListComponent/index.tsx
> +      handleOnNewValue({ value: [{ "": "" }] });
I think skipSnapshot is necessary here as well.

2024-10-04 20:05 UTC, lucaseduoli commented on src/frontend/src/components/parameterRenderComponent/components/linkComponent/index.tsx
I think there is a missing cleaning of the component value, like the other ones

2024-10-04 20:05 UTC, lucaseduoli commented on src/frontend/tests/core/unit/tableInputComponent.spec.ts
> +  let control = "Meta";
shouldn't it be Ctrl?

2024-10-04 20:08 UTC, Cristhianzl commented on src/frontend/tests/core/unit/tableInputComponent.spec.ts
> +  let control = "Meta";
yes

2024-10-07 19:02 UTC, anovazzi1 commented on src/frontend/src/components/parameterRenderComponent/components/linkComponent/index.tsx
this one the user does not change the link value directly, only using the component code, so the disabled clean up does not make sense in this case

2024-10-08 18:21 UTC, lucaseduoli approved these changes
LGTM!

2024-10-08 18:29 UTC, merged