Added alembic log path as env var change
langflow-ai/langflow pull request #4272
Opened 2024-10-24 17:15 UTC by devinbost

For OpenShift, we needed a way to override the default alembic log directory with a path that exists on a non-read-only filesystem (i.e. on a mounted path). This change (if it does what it's intended to do) will enable that.  

Intended to fix: https://github.com/langflow-ai/langflow/issues/4235

2024-10-26 13:31 UTC, cbornet requested changes

2024-10-26 13:31 UTC, cbornet commented on src/backend/base/langflow/services/database/service.py
> +        if self.settings_service.settings.alembic_log_file.startswith("/"):
Use the cross-platform [Path.is_absolute()](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_absolute)

2024-10-28 19:48 UTC, ogabrielluiz approved these changes
LGTM

2024-10-28 22:45 UTC, cbornet approved these changes

2024-10-29 10:28 UTC, merged