Add tool mode to components
langflow-ai/langflow pull request #4439
Opened 2024-11-07 06:37 UTC by edwinjosechittilappilly

@Waiting for #4402

2024-11-07 22:20 UTC, edwinjosechittilappilly commented
@ogabrielluiz  Should I merge this into your branch (#4402 )  ? or should I merge into the main once #4402 is closed?

2024-11-08 00:32 UTC, ogabrielluiz requested changes
Just this small fix and this should be good to go.

2024-11-08 00:32 UTC, ogabrielluiz commented on src/backend/base/langflow/components/agents/agent.py
> +            self.tools.append(CurrentDateComponent().to_toolkit())
You should add a check because self.tools may not be a list.

2024-11-08 00:44 UTC, ogabrielluiz approved these changes

2024-11-08 09:02 UTC, edwinjosechittilappilly commented
Tested :
With the Fix: #4465 
New agents work as expected.

2024-11-08 12:53 UTC, merged