fix: resolve lock misuse and potential deadlock in AsyncInMemoryCache
langflow-ai/langflow pull request #4464
Opened 2024-11-08 07:44 UTC by dhlidongming

This pull request resolves potential concurrency issues in cache operations by addressing two problems in the `AsyncInMemoryCache` class. 

First, it ensures that a provided `lock` object is utilized. 

Second, it refactors the `upsert` method to avoid potential deadlocks by correctly passing the lock to nested method calls such as get and set: 
In the `upsert` function:
https://github.com/langflow-ai/langflow/blob/1e4594ad43710a87402659fe402e8b22b81a71c2/src/backend/base/langflow/services/cache/service.py#L357-L360
if the lock parameter is not provided, the `self.lock` object is used to acquire a lock before calling the `_upsert` function. Within the `_upsert` function, the `get` function is invoked without a lock parameter:
https://github.com/langflow-ai/langflow/blob/1e4594ad43710a87402659fe402e8b22b81a71c2/src/backend/base/langflow/services/cache/service.py#L364-L365
which causes the `get` function to acquire the `self.lock` object again, leading to a deadlock:
https://github.com/langflow-ai/langflow/blob/1e4594ad43710a87402659fe402e8b22b81a71c2/src/backend/base/langflow/services/cache/service.py#L300-L303

2024-11-08 11:27 UTC, dhlidongming commented
The PR contains an error: the lock parameter cannot be removed, even though it is not used. 
Because the base class abstract method includes this parameter:
https://github.com/langflow-ai/langflow/blob/0bf7dda0099f6563f495a7831f0c2cb55c3e6676/src/backend/base/langflow/services/cache/base.py#L40
It will also be passed in during the call.

2024-11-08 11:48 UTC, ogabrielluiz commented
> @ogabrielluiz The PR contains an error: the lock parameter cannot be removed, even though it is not used. Because the base class abstract method includes this parameter:
> 
> https://github.com/langflow-ai/langflow/blob/0bf7dda0099f6563f495a7831f0c2cb55c3e6676/src/backend/base/langflow/services/cache/base.py#L40
> 
> 
> It will also be passed in during the call.

Hey @dhlidongming 

Thanks for this fix. 

Maybe you could pass the lock all the way down to the `get` method.

2024-11-08 20:20 UTC, cbornet commented
Could also use a rentrant lock asyncio.RLock ?

2024-11-08 20:32 UTC, cbornet commented on src/backend/base/langflow/services/cache/service.py
> -        if not lock:
Annotate the method with `@override` (from typing_extensions) to solve the ARG002 rule error.

2024-11-12 12:32 UTC, ogabrielluiz requested changes

2024-11-12 12:32 UTC, ogabrielluiz commented on src/backend/base/langflow/services/cache/service.py
why not this?
```python
    @override
    async def upsert(self, key, value, lock=None) -> None:
    	await self._upsert(key, value, lock)
    	
    async def _upsert(self, key, value, lock):
    	existing_value = await self.get(key, lock)
```

2024-11-13 07:26 UTC, dhlidongming commented on src/backend/base/langflow/services/cache/service.py
Thank you for your suggestion. I have revised the implementation to pass the `lock` down to the `get` and `set` functions as you recommended. I've just submitted a new commit with these changes.

2024-11-14 10:25 UTC, ogabrielluiz approved these changes
LGTM

2024-11-14 11:44 UTC, merged