feat: Implement new Langflow Logo for uplift throughout the application
langflow-ai/langflow pull request #4509
Opened 2024-11-11 20:40 UTC by mfortman11

Updates the application to use the new logo

![Screenshot 2024-11-11 at 1 00 43 PM](https://github.com/user-attachments/assets/7584cd1e-7cf7-44b7-8ff8-a4bb0df0ddd2)
![Screenshot 2024-11-11 at 1 00 29 PM](https://github.com/user-attachments/assets/268240a8-ad74-4498-8623-0f4ac58d8843)

![Screenshot 2024-11-11 at 12 58 25 PM](https://github.com/user-attachments/assets/f1d0f45b-87d3-4630-918f-d5063729ff05)
![Screenshot 2024-11-11 at 1 00 11 PM](https://github.com/user-attachments/assets/102f4dad-2410-443d-8cc6-30d0abcc5e07)

![Screenshot 2024-11-11 at 12 58 11 PM](https://github.com/user-attachments/assets/f455899b-1f2c-41e4-8db9-6940da1785b2)
![Screenshot 2024-11-11 at 1 00 02 PM](https://github.com/user-attachments/assets/346b3311-7fc2-4471-942f-68b9d87d28b2)

2024-11-11 21:05 UTC, Cristhianzl approved these changes
lgtm

2024-11-11 21:06 UTC, Cristhianzl requested changes
just some small adjustments

2024-11-11 21:06 UTC, Cristhianzl commented on src/frontend/src/pages/SignUpPage/index.tsx
> +              className="mb-4 h-[40px] w-[40px] scale-[1.5]"
can we change this to `h-10`?

2024-11-11 21:06 UTC, Cristhianzl commented on src/frontend/src/pages/LoginPage/index.tsx
> +              className="mb-4 h-[40px] w-[40px] scale-[1.5]"
can we change this to `h-10 w-10`?

2024-11-11 21:06 UTC, Cristhianzl commented on src/frontend/src/pages/DeleteAccountPage/index.tsx
> +            className="mb-4 h-[40px] w-[40px] scale-[1.5]"
can we change this to` h-10 w-10`?

2024-11-11 21:06 UTC, Cristhianzl commented on src/frontend/src/pages/AdminPage/LoginPage/index.tsx
> +            className="h-[40px] w-[40px] scale-[1.5]"
can we change this to` h-10 w-10`?

2024-11-11 21:06 UTC, Cristhianzl commented on src/frontend/src/modals/IOModal/components/chatView/newChatView.tsx
> +                  className="h-[40px] w-[40px] scale-[1.5]"
can we change this to` h-10 w-10`?

2024-11-11 21:06 UTC, Cristhianzl commented on src/frontend/src/modals/IOModal/components/chatView/newChatView.tsx
> +                  className="h-[40px] w-[40px] scale-[1.5]"
can we change this to` h-10 w-10`?

2024-11-11 21:38 UTC, Cristhianzl approved these changes
LGTM

2024-11-11 22:21 UTC, mfortman11 commented on src/frontend/index.html
> +    <link rel="icon" href="/favicon2.ico" />
named favicon2 for cache busting purposes can change back to favicon after a release or 2

2024-11-11 22:22 UTC, mfortman11 commented on src/frontend/src/components/appHeaderComponent/index.tsx
> +        {ENABLE_DATASTAX_LANGFLOW && (
Corrects feature flag logic

2024-11-12 13:35 UTC, anovazzi1 approved these changes
lgtm

2024-11-12 17:37 UTC, merged