refactor: Improve componentHoverAdd.spec test
langflow-ai/langflow pull request #4608
Opened 2024-11-14 16:55 UTC by anovazzi1

Refactor the componentHoverAdd.spec.ts file to improve performance

2024-11-14 17:15 UTC, lucaseduoli approved these changes
LGTM

2024-11-22 02:18 UTC, ogabrielluiz requested changes

2024-11-22 02:18 UTC, ogabrielluiz commented on src/frontend/tests/core/features/componentHoverAdd.spec.ts
> +  expect(opacity).toBe("0");
```suggestion
  await expect(opacity).toBe("0");
```

2024-11-22 02:19 UTC, ogabrielluiz approved these changes

2024-11-22 03:14 UTC, merged