feat: add needle as custom component
langflow-ai/langflow pull request #4657
Opened 2024-11-17 17:12 UTC by JANHMS

## Overview
Really cool project, I like it. Looking forward to integrate and work with you. 

* Adding Needle as a Component to Langflow.

## Depends on
Depends on my other PR, where I contribute Needle to Langchain. 
https://github.com/langchain-ai/langchain/pull/28157

2024-12-07 16:06 UTC, JANHMS commented
Picking this up now again, since Needle is now officially available in Langchain Community Package:

https://python.langchain.com/docs/integrations/retrievers/needle/

2024-12-10 12:34 UTC, ogabrielluiz requested changes
Hey @JANHMS 

How are you?

Thank you for this!

2024-12-10 12:34 UTC, ogabrielluiz commented on src/backend/base/langflow/components/needle/needle.py
This inherits from `CustomComponent` instead of `Component` which is the standard since `1.0`. 

ChatGPT or our Custom Component Generator template might be able to help you migrate it. You can use an example component like `NotDiamondComponent`.

2024-12-12 08:00 UTC, JANHMS commented on src/backend/base/langflow/components/needle/needle.py
Thanks man! Will have a look!

2024-12-14 17:05 UTC, JANHMS commented on src/backend/base/langflow/components/needle/needle.py
@ogabrielluiz I adjusted now. Works fine.

2024-12-14 17:58 UTC, JANHMS commented
@ogabrielluiz worked on this a bit this Saturday afternoon. Should be ok now using the Component and being able to be used with other components.

2024-12-16 11:44 UTC, ogabrielluiz approved these changes

2024-12-16 15:11 UTC, merged