fix: Use AsyncSession in memory
langflow-ai/langflow pull request #4665
Opened 2024-11-18 12:06 UTC by cbornet

Use AsyncSession in memory

2024-11-18 12:18 UTC, ogabrielluiz requested changes
Hey @cbornet 

Have you checked the `ComponentTestBase`(https://github.com/langflow-ai/langflow/blob/a7aa3ab03f309e8303dc230b1816d14f6d322e2f/src/backend/tests/unit/components/inputs/test_input_components.py#L10)? 

Maybe we can build these for the components you've changed to make sure they don't break in future releases.

2024-11-18 13:15 UTC, cbornet commented
@ogabrielluiz I fixed `TestChatInput`. Can you check again ?

2024-11-26 00:37 UTC, ogabrielluiz commented
Hey @cbornet 

This is a very dangerous PR so we'll wait until next week to merge it. Just in case we need to release a patch this week.

2024-12-04 14:58 UTC, ogabrielluiz approved these changes

2024-12-06 16:25 UTC, merged