Made logformat configurable
langflow-ai/langflow pull request #4851
Opened 2024-11-26 08:53 UTC by Kraego

Since i had problems with the encoding of the colored json log in the OKD shell (see Image), I've made the logformat configurable.

![image](https://github.com/user-attachments/assets/1e15fa2d-8ecb-4e3d-94b3-0313b44c9511)

2024-11-26 09:43 UTC, Kraego commented
Would it be better to use `LANGFLOW_LOG_ENV`? Just found the variable in the code, currently there is no decription in the environments_variables.md for this setting.

2024-11-26 12:38 UTC, ogabrielluiz commented
Hey @Kraego 

How are you? 

This is a valid problem. If we were to use LANGFLOW_ENV we'd have to build something like the following to check for valid format strings:
```python
import logging

def is_valid_log_format(format_string):
    """Validates a logging format string by attempting to format it with a dummy LogRecord.

    Args:
        format_string (str): The format string to validate.

    Returns:
        bool: True if the format string is valid, False otherwise.
        str: Error message if invalid, empty string if valid.
    """
    record = logging.LogRecord(
        name="dummy",
        level=logging.INFO,
        pathname="dummy_path",
        lineno=0,
        msg="dummy message",
        args=None,
        exc_info=None
    )

    formatter = logging.Formatter(format_string)

    try:
        # Attempt to format the record
        formatter.format(record)
    except (KeyError, ValueError, TypeError) as e:
        # Formatting failed, return False and the error message
        msg = f"Invalid log format string: {format_string}"
        raise ValueError(msg) from e
    return True

```

What do you think?

2024-11-26 17:07 UTC, ogabrielluiz approved these changes
Thanks @Kraego !

LGTM

2024-11-26 19:56 UTC, Kraego commented
@ogabrielluiz now ready for merge

2024-11-26 22:05 UTC, ogabrielluiz commented
Hey @Kraego 

Sounds good! 

I'll merge it ASAP. You can leave it out of date because it will only merge when no other PR is merging.

2024-11-26 22:06 UTC, ogabrielluiz requested changes

2024-11-26 22:06 UTC, ogabrielluiz commented on src/backend/base/langflow/logging/logger.py
> +        return False
I feel like we should log an error here so the user know why their log format isn't working.

2024-11-27 14:19 UTC, ogabrielluiz approved these changes

2024-11-27 14:28 UTC, merged