test: Enhance frontend testability with data attributes and integration tests
langflow-ai/langflow pull request #4948
Opened 2024-11-29 16:57 UTC by Cristhianzl

This pull request includes several updates to the frontend components and the addition of new integration tests. The most important changes include adding `data-testid` attributes to various components for better testability, importing utilities for test name conversion, and creating new integration tests for different functionalities.

### Enhancements to Components:

* [`src/frontend/src/components/core/codeTabsComponent/ChatCodeTabComponent.tsx`](diffhunk://#diff-8ce41c2128c463f03a37bcb819dddc54c0078285609da848b3650a8b4e10eb70L34-R37): Added `data-testid="chat-code-tab"` to the main div for better testability.
* [`src/frontend/src/modals/templatesModal/components/TemplateCardComponent/index.tsx`](diffhunk://#diff-1643e0ff92f1725e30e22c7126de047d2a2bc79af6097ef5e6191801e42bfbb2R28): Added `data-testid` attribute to the template card div for better testability.
* [`src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/sidebarDraggableComponent/index.tsx`](diffhunk://#diff-c94382f8e218f4b5d129a9052c8e0754e1b9cb791d077f41b4499442a4fefc6bR180-R182): Added `data-testid` attributes to the add component button for better testability.

### Utility Imports:

* [`src/frontend/src/pages/FlowPage/components/flowSidebarComponent/components/sidebarDraggableComponent/index.tsx`](diffhunk://#diff-c94382f8e218f4b5d129a9052c8e0754e1b9cb791d077f41b4499442a4fefc6bR1): Imported `convertTestName` utility for converting test names.

### New Integration Tests:

* [`src/frontend/tests/core/integrations/Custom Component Generator.spec.ts`](diffhunk://#diff-d914f41b7bd3fca12fd73e47e07d28542a0c70076f89767d5fbb600eed61e726R1-R134): Added a comprehensive integration test for the Custom Component Generator.
* [`src/frontend/tests/core/integrations/Image Sentiment Analysis.spec.ts`](diffhunk://#diff-96295b914908ecaba76a7dd10e21e2f8a235a925464af85d0861dfe038435216R1-R144): Added a comprehensive integration test for Image Sentiment Analysis.
* [`src/frontend/tests/core/integrations/Instagram Copywriter.spec.ts`](diffhunk://#diff-3db0aba29df2ab29061fce72d7fa44970c24733857915f4e2be1c418fbf48ce5R1-R133): Added a comprehensive integration test for Instagram Copywriter.
* [`src/frontend/tests/core/integrations/Market Research.spec.ts`](diffhunk://#diff-9054a67e36b20189ebf96d7347009b67d17a4c098269f2d1f6e870385ca5ac29R1-R133): Added a comprehensive integration test for Market Research.
* [`src/frontend/tests/core/integrations/Prompt Chaining.spec.ts`](diffhunk://#diff-e72392d6056c3cf2dc5dfcc0bef7abf3b7dfcdb16f4bf8d6e0e084028f11366dR1-R133): Added a comprehensive integration test for Prompt Chaining.

2024-11-29 18:38 UTC, anovazzi1 approved these changes
lgtm

2024-11-30 18:18 UTC, ogabrielluiz approved these changes

2024-11-30 20:13 UTC, ogabrielluiz requested changes
There's a problem in one of the changes you made in the workflow files. Possibly the quotes

2024-12-04 16:40 UTC, ogabrielluiz approved these changes

2024-12-04 16:49 UTC, merged