Update store_message.py
langflow-ai/langflow pull request #4954
Opened 2024-11-29 19:17 UTC by edwinjosechittilappilly

Update stored message to give out only the latest message.
This pull request includes changes to the `StoreMessageComponent` class in the `store_message.py` file to improve the handling of stored messages. The most important changes include renaming an output and modifying the `store_message` method to use more efficient message retrieval logic.

Changes to output naming:

* [`src/backend/base/langflow/components/helpers/store_message.py`](diffhunk://#diff-c873d4f3dd80c34e0163a9060b7a116f076e62e99e5105a0fe11b4e06f99a0faL47-R47): Renamed the output from "Stored Messages" to "Stored Message" to reflect that only a single message is stored.

Improvements to message retrieval logic:

* [`src/backend/base/langflow/components/helpers/store_message.py`](diffhunk://#diff-c873d4f3dd80c34e0163a9060b7a116f076e62e99e5105a0fe11b4e06f99a0faL65-R73): Modified the `store_message` method to use the `next` function for retrieving messages, ensuring that only the first matching message is returned, and added a default value of `None` if no messages match.

2024-11-29 21:07 UTC, ogabrielluiz requested changes
Hey @edwinjosechittilappilly 

Why was this done? Can't we just get `store[0]`?

2024-11-29 21:49 UTC, edwinjosechittilappilly commented
@ogabrielluiz  
I had corrected it with the suggested approach. Earlier, I used next to provide the default case. Yea, but you were right.

2024-12-11 15:03 UTC, anovazzi1 approved these changes
lgtm

2024-12-11 17:36 UTC, edwinjosechittilappilly commented
@ogabrielluiz  can you review it once available?

2024-12-11 17:39 UTC, ogabrielluiz requested changes

2024-12-11 17:39 UTC, ogabrielluiz commented on src/backend/base/langflow/components/helpers/store_message.py
>              )
```suggestion
            stored_messages = await aget_messages(
                session_id=message.session_id, sender_name=message.sender_name, sender=message.sender
            )
            if not stored_messages:
            	raise SomeError
            stored_message = stored_messages[0]
            
            
```

2024-12-11 18:26 UTC, edwinjosechittilappilly commented
@ogabrielluiz  I had made the changes requested.

2024-12-16 18:26 UTC, ogabrielluiz approved these changes

2024-12-16 18:56 UTC, merged