refactor(components): Rename StoreMessage to MessageStore for Better Clarity
langflow-ai/langflow pull request #5009
Opened 2024-12-02 20:10 UTC by Vigtu

# Changes in Message Store Component:

## Component Rename:
1. StoreMessage -> MessageStore:
- Renamed class from StoreMessageComponent to MessageStoreComponent
- Updated display name to "Message Store"
- Changed icon from "save" to "message-square-text"
- Updated component name to "MessageStore"

## Output Configuration:
- Added hidden=True to stored_messages output

## Import Updates:
- Updated import in __init__.py:
  * store_message -> message_store
  * StoreMessageComponent -> MessageStoreComponent

## File Rename:
- store_message.py -> message_store.py

## No Functional Changes:
- Core functionality remains the same
- Only naming and cosmetic changes applied
- Component description maintained

2024-12-06 19:31 UTC, erichare commented
@Vigtu same for this one, if you don't mind fixing the merge conflict i'll do a review!

2024-12-09 23:39 UTC, ogabrielluiz requested changes
Hey @Vigtu 

Thanks for the PR! 

When changing componentes we shouldn't change the file name AND the name. You must keep one as it is for backwards compatibility. 

You should be better off reverting the change to the name attribute. 

Also, if you could add tests to this component like you can see in src/backend/tests/unit/components/../test_input_components.py it would be really good. 


Thanks!

2024-12-09 23:39 UTC, ogabrielluiz commented on src/backend/base/langflow/components/helpers/message_store.py
> +    name = "MessageStore"
This breaks backwards compatibility

2024-12-19 12:30 UTC, ogabrielluiz approved these changes
LGTM

2024-12-19 19:31 UTC, erichare approved these changes

2024-12-19 19:32 UTC, merged