feature: Add message feedback and update frontend interface
langflow-ai/langflow pull request #5022
Opened 2024-12-03 13:41 UTC by anovazzi1

This pull request includes commits that add message feedback and update the frontend interface.

2024-12-09 11:59 UTC, italojohnny approved these changes

2024-12-13 12:28 UTC, italojohnny approved these changes

2024-12-13 12:37 UTC, ogabrielluiz requested changes
`good_answer` is not a good name. 

Maybe `positive_feedback`?

2024-12-13 20:28 UTC, ogabrielluiz approved these changes

2024-12-17 19:09 UTC, merged