feat: enhance slider component with labels and improved input handling
langflow-ai/langflow pull request #5065
Opened 2024-12-04 19:13 UTC by Cristhianzl

This pull request includes several changes to the frontend and backend components to enhance the functionality and user experience of the slider component.

### Frontend Changes:

* **Slider Component Enhancements:**
  * Added `SliderLabels` component to display min and max labels with icons for the slider. (`src/frontend/src/components/core/parameterRenderComponent/components/sliderComponent/components/slider-labels.tsx`, [src/frontend/src/components/core/parameterRenderComponent/components/sliderComponent/components/slider-labels.tsxR1-R46](diffhunk://#diff-c0a9aab2ee867a10e8c618c0115c8b91ce59ba8a615f9a36a9b2b6de9ea5542aR1-R46))
  * Modified the slider component to include new states and handlers for input changes, blur, and key down events. (`src/frontend/src/components/core/parameterRenderComponent/components/sliderComponent/index.tsx`, [src/frontend/src/components/core/parameterRenderComponent/components/sliderComponent/index.tsxR136-R202](diffhunk://#diff-6958133e6992160edd970404518b518af12d81049a6562bdcb8264fad54e272dR136-R202))
  * Updated the slider's step value to 0.01 and changed the max label from "Wild" to "Creative". (`src/frontend/src/components/core/parameterRenderComponent/components/sliderComponent/index.tsx`, [[1]](diffhunk://#diff-6958133e6992160edd970404518b518af12d81049a6562bdcb8264fad54e272dL29-R29) [[2]](diffhunk://#diff-6958133e6992160edd970404518b518af12d81049a6562bdcb8264fad54e272dL63-R62)

* **CSS Adjustments:**
  * Added new CSS rules to hide spin buttons for number inputs and styled the slider input text. (`src/frontend/src/App.css`, [[1]](diffhunk://#diff-3e7904848c381eb53375a14db869438235df15b6e439845f23d09b12382c0d47R194-R199); `src/frontend/src/style/applies.css`, [[2]](diffhunk://#diff-f227a8805837a247ce52fbbc51e193ce8de9e83c5810af44a0887ee4d888baa2R1275-R1278)

### Backend Changes:

* **OpenAI Model Component Update:**
  * Adjusted the `temperature` slider input range specification to allow values between 0 and 2 with a step of 0.01. (`src/backend/base/langflow/components/models/openai.py`, [src/backend/base/langflow/components/models/openai.pyL73-R75](diffhunk://#diff-315722d3776898e43e8f0e24de9a20f816f2b2fd5ada9fe5e4180ce3eb262206L73-R75))

2024-12-04 19:27 UTC, anovazzi1 requested changes

2024-12-04 19:27 UTC, anovazzi1 commented on src/frontend/src/style/applies.css
can we use a a css variable instead of a direct hex color on it?

2024-12-04 19:58 UTC, Cristhianzl commented on src/frontend/src/style/applies.css
sure!

2024-12-05 18:16 UTC, anovazzi1 approved these changes
lgtm

2024-12-06 13:03 UTC, merged