refactor(openai): Remove deprecated parameters from OpenAI component
langflow-ai/langflow pull request #5171
Opened 2024-12-09 21:59 UTC by raphaelchristi

## Changes
- Removed deprecated `output_schema` parameter
- Removed redundant `output_parser` parameter
- Simplified JSON output handling to use only `json_mode`

## Why
This PR cleans up the OpenAI component by:
1. Removing deprecated functionality that was marked for removal
2. Simplifying the way we handle structured outputs by relying solely on `json_mode`
3. Making the component more maintainable by reducing redundant parameters

## Testing
The changes maintain all essential functionality while removing deprecated features. JSON output can still be achieved using the `json_mode` parameter.

2024-12-09 23:32 UTC, ogabrielluiz requested changes
Hey @raphaelchristi 

Thanks for the PR. 

If you remove inputs you must also change that code that references them, otherwise we might run into problems.

2024-12-10 14:28 UTC, ogabrielluiz approved these changes
LGTM

2024-12-10 14:45 UTC, merged

2024-12-13 02:24 UTC, edwinjosechittilappilly commented
@ogabrielluiz  This change would have triggered few errors.

Should we remove output_parser from other LLM components?

2024-12-13 06:07 UTC, edwinjosechittilappilly commented
fix: https://github.com/langflow-ai/langflow/pull/5242