feat: adding tool mode to LC model component
langflow-ai/langflow pull request #5174
Opened 2024-12-10 01:24 UTC by edwinjosechittilappilly

This pull request includes updates to the `MessageInput` class and enhancements to the `LCModelComponent` class to improve functionality and user experience.

Features:

- tool_mode added
- info for inputs updated
- added toolmixin for message input DataType.

Enhancements to `LCModelComponent`:

* [`src/backend/base/langflow/base/models/model.py`](diffhunk://#diff-7f05be33af0d7c390019c835f3473dd4e5aa8a73bb723fc382bb1b04b2874632L28-R33): Added additional attributes to `MessageInput`, such as `info` and `tool_mode`, to provide more context and functionality for the input field.

Updates to `MessageInput` class:

* [`src/backend/base/langflow/inputs/inputs.py`](diffhunk://#diff-f12c9ca218a67d203869442cb70537349ad1f026a3c20c88c8f1e15ae71bdbc8L147-R147): Modified `MessageInput` to inherit from `ToolModeMixin`, enhancing its capabilities by integrating tool mode functionality.

2024-12-10 11:41 UTC, ogabrielluiz requested changes
Hey @edwinjosechittilappilly 

I'm not sure this will work because the MessageInput needs a valid Message to be passed. 

Also, why would an Agent use an LLM as a tool?

2024-12-11 21:17 UTC, edwinjosechittilappilly commented
https://www.loom.com/share/d8fc8fd597db4fbbbc35e288afb0e3ea?sid=6ac19a43-3378-4f96-9c6b-cb5f67967471

2024-12-11 21:21 UTC, edwinjosechittilappilly commented
@ogabrielluiz This was a PoC request. 

ref: @carlosrcoelho @rodrigosnader 

I had tested it just now. This could be used if we need LLM to perform certain stand-alone tasks.

We, even I, had a similar thought: should we have this functionality?
I am looking forward to your guidance on should we proceed with this update? (ignore the first error in demo, due to API rate limits)

2024-12-13 17:29 UTC, edwinjosechittilappilly commented
PoC:

Closed until further requirement.

2024-12-13 17:29 UTC, closed without merging