fix: agents issue | remove depreciated feature output parser
langflow-ai/langflow pull request #5242
Opened 2024-12-13 02:33 UTC by edwinjosechittilappilly

Solved:   AttributeError: output_parser not found in AgentComponent  

Issue Triggered by removal of Output_parser only from the OpenAI Component.
   
This pull request includes several changes to the `src/backend/base/langflow/components/models` directory, primarily focusing on the removal of the `HandleInput` import and associated `HandleInput` configurations from various model component files. Additionally, a TODO comment has been added to a method in the `model.py` file.

### Removal of `HandleInput`:

* [`src/backend/base/langflow/components/models/aiml.py`](diffhunk://#diff-917001f51aa49f87771ffa8367e0af7daad7b2c68ff041e2d879581215d7c7ccL10): Removed `HandleInput` import and configuration for `output_parser` in `AIMLModelComponent`. [[1]](diffhunk://#diff-917001f51aa49f87771ffa8367e0af7daad7b2c68ff041e2d879581215d7c7ccL10) [[2]](diffhunk://#diff-917001f51aa49f87771ffa8367e0af7daad7b2c68ff041e2d879581215d7c7ccL52-L58)
* [`src/backend/base/langflow/components/models/amazon_bedrock.py`](diffhunk://#diff-57bef73d53b4274a63bd1dd6c8db08212fde98d11203515e26ea4f63cd4e9cc1L5): Removed `HandleInput` import and configuration for `output_parser` in `AmazonBedrockComponent`. [[1]](diffhunk://#diff-57bef73d53b4274a63bd1dd6c8db08212fde98d11203515e26ea4f63cd4e9cc1L5) [[2]](diffhunk://#diff-57bef73d53b4274a63bd1dd6c8db08212fde98d11203515e26ea4f63cd4e9cc1L76-L82)
* [`src/backend/base/langflow/components/models/anthropic.py`](diffhunk://#diff-cdc04b2d3c1d72c0075212c06edcb78b3dbc7f32b34cb7f9486272d2a6725347L6): Removed `HandleInput` import and configuration for `output_parser` in `AnthropicModelComponent`. [[1]](diffhunk://#diff-cdc04b2d3c1d72c0075212c06edcb78b3dbc7f32b34cb7f9486272d2a6725347L6) [[2]](diffhunk://#diff-cdc04b2d3c1d72c0075212c06edcb78b3dbc7f32b34cb7f9486272d2a6725347L43-L49)
* [`src/backend/base/langflow/components/models/azure_openai.py`](diffhunk://#diff-b0bd5234d722d05104d938f39dd83658e571f21a4b371dbdda610157baeb774eL6): Removed `HandleInput` import and configuration for `output_parser` in `AzureChatOpenAIComponent`. [[1]](diffhunk://#diff-b0bd5234d722d05104d938f39dd83658e571f21a4b371dbdda610157baeb774eL6) [[2]](diffhunk://#diff-b0bd5234d722d05104d938f39dd83658e571f21a4b371dbdda610157baeb774eL60-L66)
* [`src/backend/base/langflow/components/models/baidu_qianfan_chat.py`](diffhunk://#diff-270b0bb3b56ff40f646d4e5e51d7292ac66d06de1c61bd392ec0d6ad1a28bc81L6): Removed `HandleInput` import and configuration for `output_parser` in `QianfanChatEndpointComponent`. [[1]](diffhunk://#diff-270b0bb3b56ff40f646d4e5e51d7292ac66d06de1c61bd392ec0d6ad1a28bc81L6) [[2]](diffhunk://#diff-270b0bb3b56ff40f646d4e5e51d7292ac66d06de1c61bd392ec0d6ad1a28bc81L70-L76)
* [`src/backend/base/langflow/components/models/cohere.py`](diffhunk://#diff-74a6b408cc305fe726086a1d66b9f96b03bd8d7059819baa2f3ae1d1612c917bL6): Removed `HandleInput` import and configuration for `output_parser` in `CohereComponent`. [[1]](diffhunk://#diff-74a6b408cc305fe726086a1d66b9f96b03bd8d7059819baa2f3ae1d1612c917bL6) [[2]](diffhunk://#diff-74a6b408cc305fe726086a1d66b9f96b03bd8d7059819baa2f3ae1d1612c917bL27-L33)
* [`src/backend/base/langflow/components/models/google_generative_ai.py`](diffhunk://#diff-d3e836d82e6d361104bdb14bced5f4812c33eab08ce1fd97bc90dbaeaa518476L7): Removed `HandleInput` import and configuration for `output_parser` in `GoogleGenerativeAIComponent`. [[1]](diffhunk://#diff-d3e836d82e6d361104bdb14bced5f4812c33eab08ce1fd97bc90dbaeaa518476L7) [[2]](diffhunk://#diff-d3e836d82e6d361104bdb14bced5f4812c33eab08ce1fd97bc90dbaeaa518476L53-L59)
* [`src/backend/base/langflow/components/models/groq.py`](diffhunk://#diff-7414ffdd84304d27ef12b28eac37735e40d3578ca9023e5d884d3e375afcb8b9L8): Removed `HandleInput` import and configuration for `output_parser` in `GroqModel`. [[1]](diffhunk://#diff-7414ffdd84304d27ef12b28eac37735e40d3578ca9023e5d884d3e375afcb8b9L8) [[2]](diffhunk://#diff-7414ffdd84304d27ef12b28eac37735e40d3578ca9023e5d884d3e375afcb8b9L55-L61)
* [`src/backend/base/langflow/components/models/huggingface.py`](diffhunk://#diff-664df391148fe55fbe880ae1322ec214f454110dcc130a4b73c5935c4239a596L10): Removed `HandleInput` import and configuration for `output_parser` in `HuggingFaceEndpointsComponent`. [[1]](diffhunk://#diff-664df391148fe55fbe880ae1322ec214f454110dcc130a4b73c5935c4239a596L10) [[2]](diffhunk://#diff-664df391148fe55fbe880ae1322ec214f454110dcc130a4b73c5935c4239a596L78-L84)
* [`src/backend/base/langflow/components/models/lmstudiomodel.py`](diffhunk://#diff-ed909b08aedd90a891a1da6a22826a994b10ce95ab806371662eb6dfbf8e9da4L12): Removed `HandleInput` import and configuration for `output_parser` in `LMStudioModelComponent`. [[1]](diffhunk://#diff-ed909b08aedd90a891a1da6a22826a994b10ce95ab806371662eb6dfbf8e9da4L12) [[2]](diffhunk://#diff-ed909b08aedd90a891a1da6a22826a994b10ce95ab806371662eb6dfbf8e9da4L87-L93)
* [`src/backend/base/langflow/components/models/maritalk.py`](diffhunk://#diff-9b91112da16c8fff5a934d6fc921cf51dd890d731e3b18df12f81f9a000f33d5L7): Removed `HandleInput` import and configuration for `output_parser` in `MaritalkModelComponent`. [[1]](diffhunk://#diff-9b91112da16c8fff5a934d6fc921cf51dd890d731e3b18df12f81f9a000f33d5L7) [[2]](diffhunk://#diff-9b91112da16c8fff5a934d6fc921cf51dd890d731e3b18df12f81f9a000f33d5L38-L44)
* [`src/backend/base/langflow/components/models/mistral.py`](diffhunk://#diff-8f8ccc56afe6087b77aa64136ebdabbf868a6c673783252900cc9350adec1762L6): Removed `HandleInput` import and configuration for `output_parser` in `MistralAIModelComponent`. [[1]](diffhunk://#diff-8f8ccc56afe6087b77aa64136ebdabbf868a6c673783252900cc9350adec1762L6) [[2]](diffhunk://#diff-8f8ccc56afe6087b77aa64136ebdabbf868a6c673783252900cc9350adec1762L58-L64)
* [`src/backend/base/langflow/components/models/nvidia.py`](diffhunk://#diff-9497a9d3010368c344c0dad0b1b04a8b84f2be1617da122437b70fc227d821a0L6): Removed `HandleInput` import and configuration for `output_parser` in `NVIDIAModelComponent`. [[1]](diffhunk://#diff-9497a9d3010368c344c0dad0b1b04a8b84f2be1617da122437b70fc227d821a0L6) [[2]](diffhunk://#diff-9497a9d3010368c344c0dad0b1b04a8b84f2be1617da122437b70fc227d821a0L52-L58)
* [`src/backend/base/langflow/components/models/ollama.py`](diffhunk://#diff-3584b0a4574f7cf4de3c66d51528edfc3c760e3aabdf06f4376b981390467c85L9): Removed `HandleInput` import and configuration for `output_parser` in `OllamaModelComponent`. [[1]](diffhunk://#diff-3584b0a4574f7cf4de3c66d51528edfc3c760e3aabdf06f4376b981390467c85L9) [[2]](diffhunk://#diff-3584b0a4574f7cf4de3c66d51528edfc3c760e3aabdf06f4376b981390467c85L169-L175)
* [`src/backend/base/langflow/components/models/perplexity.py`](diffhunk://#diff-49fe51485a89854ae64ed91693c039ad798520893e5128420938aaf084353812L6): Removed `HandleInput` import and configuration for `output_parser` in `PerplexityComponent`. [[1]](diffhunk://#diff-49fe51485a89854ae64ed91693c039ad798520893e5128420938aaf084353812L6) [[2]](diffhunk://#diff-49fe51485a89854ae64ed91693c039ad798520893e5128420938aaf084353812L63-L69)
* [`src/backend/base/langflow/components/models/sambanova.py`](diffhunk://#diff-317b5f6acc6de2b96ea53d4a2b35a96b3765d4b050af04db712e47ea748de55cL7): Removed `HandleInput` import from `SambanovaModelComponent`.

### Deprecated Feature Notice:

* [`src/backend/base/langflow/base/models/model.py`](diffhunk://#diff-7f05be33af0d7c390019c835f3473dd4e5aa8a73bb723fc382bb1b04b2874632R178): Added a TODO comment indicating that a feature is deprecated and will be removed in the future.

2024-12-13 18:11 UTC, ogabrielluiz requested changes
If you remove the Input named `output_parser` from the list, calling `self.output_parser` will raise an `AttributeError`. You need add a `hasattr` check before checking if it is None.

2024-12-16 06:02 UTC, edwinjosechittilappilly commented
> If you remove the Input named `output_parser` from the list, calling `self.output_parser` will raise an `AttributeError`. You need add a `hasattr` check before checking if it is None.

Can we remove the line that uses self.output_parser since it's already deprecated?
I added the check as suggested. But I believe we can remove it completely in an upcoming release or in the current release.

2024-12-16 11:34 UTC, ogabrielluiz requested changes

2024-12-16 15:18 UTC, edwinjosechittilappilly commented
Tested.

2024-12-16 15:38 UTC, ogabrielluiz approved these changes

2024-12-16 16:04 UTC, merged