feat: add new model provider Novita AI
langflow-ai/langflow pull request #5380
Opened 2024-12-20 11:29 UTC by jasonhp

Add new model provider: [Novita AI](https://novita.ai?utm_source=github_langflow&utm_medium=github_readme&utm_campaign=link)

2024-12-27 09:02 UTC, jasonhp commented
@ogabrielluiz Hello! I saw many PRs come across this Codeflash error and was wondering if anyone could fix it. Thanks in advance!

2024-12-27 17:28 UTC, ogabrielluiz commented
hey @jasonhp 

Thanks for the new component! 


The codeflash action does not run on external PRs. It won't block merging, though, so we are good here.

2025-01-03 03:18 UTC, jasonhp commented
> hey @jasonhp
> 
> Thanks for the new component!
> 
> The codeflash action does not run on external PRs. It won't block merging, though, so we are good here.

Thank you for getting back to me! Just to confirm – are we waiting for the code review now? Do you have an estimate on when it might be completed?

2025-01-03 11:36 UTC, ogabrielluiz requested changes
Hey @jasonhp 

Thanks!

Just a couple of comments.

2025-01-03 11:36 UTC, ogabrielluiz commented on src/backend/base/langflow/components/models/novita.py
> +            value="NOVITA_API_KEY",
If you search for `VARIABLES_TO_GET_FROM_ENVIRONMENT` you'll find a list of variables that Langflow looks for in the environment and automatically creates a global variable for it. Feel free to add `NOVITA_API_KEY` there.

2025-01-03 11:36 UTC, ogabrielluiz commented on src/backend/base/langflow/components/models/novita.py
> +        if field_name in {"api_key", "model_name"}:
`api_key` is not set as a `real_time_refresh=True` or `refresh_button=True` so it will never show up here. Is that intented?

2025-01-07 03:08 UTC, jasonhp commented on src/backend/base/langflow/components/models/novita.py
> +            value="NOVITA_API_KEY",
Added

2025-01-07 03:09 UTC, jasonhp commented on src/backend/base/langflow/components/models/novita.py
> +        if field_name in {"api_key", "model_name"}:
Added real_time_refresh=True for that input

2025-01-09 07:53 UTC, jasonhp commented
@ogabrielluiz Hello! I believe all the comments have been addressed. I would greatly appreciate it if you could approve this PR.

2025-01-20 13:14 UTC, merged