feat: Introduced YouTube bundle with essential components
langflow-ai/langflow pull request #5415
Opened 2024-12-23 22:28 UTC by raphaelchristi

## Description
This pull request introduces a set of components for YouTube integration, enabling the retrieval and analysis of video data, channels, playlists, comments, trending content, searches, and transcriptions. These components leverage the YouTube API to provide robust and configurable functionalities.

## Components

### 1. YouTube Channel Component
Retrieves detailed information about YouTube channels, including:
- Channel statistics
- Branding settings
- Public playlists
- *Requires YouTube API key*

### 2. YouTube Comments Component
Retrieves and analyzes YouTube video comments, featuring:
- Comment threads
- Reply chains
- Engagement metrics
- *Requires YouTube API key*

### 3. YouTube Video Details Component
Provides comprehensive video information, including:
- Video statistics
- Content details
- Tags and thumbnails
- *Requires YouTube API key*

### 4. YouTube Playlist Component
Retrieves and analyzes playlist information:
- Video details within playlists
- Playlist statistics
- Playlist metadata
- *Requires YouTube API key*

### 5. YouTube Trending Component
Retrieves trending YouTube videos:
- Filtering by region
- Category filtering
- Trending metrics
- *Requires YouTube API key*

### 6. YouTube Search Component
Performs YouTube searches and returns video data:
- Search results processing
- Filter options
- Result pagination
- *Requires YouTube API key*

### 7. YouTube Transcripts Component
Extracts spoken content from YouTube videos:
- Multiple format options
- Translation capabilities
- Timestamp alignment
- *No API key required*

## Technical Notes
- All components except the Transcripts Component require a YouTube API key
- Features are configurable through various input parameters to meet user requirements
- Components are designed for seamless integration into existing workflows
- All components provide structured data output for easy analysis
- Integration supports error handling and rate limiting considerations

This implementation provides valuable insights and data extraction capabilities while maintaining a clean and modular architecture.

2025-01-16 11:35 UTC, ogabrielluiz requested changes
Hey @raphaelchristi 

Since these are all new components, you don't need to set the `name` attribute in them.

2025-01-16 17:55 UTC, ogabrielluiz approved these changes

2025-01-16 17:55 UTC, ogabrielluiz approved these changes

2025-01-18 01:03 UTC, edwinjosechittilappilly commented
@Cristhianzl can you check the frontend test ?

2025-01-20 18:49 UTC, merged