refactor(component): Convert Tavily Search to standard component pattern
langflow-ai/langflow pull request #5430
Opened 2024-12-24 22:25 UTC by raphaelchristi

This pull request modifies the Tavily Search component to follow the standard component pattern used in components like URL fetcher. The main changes are:

- Converts from LCToolComponent to Component to support direct data and text outputs
- Removes tool-specific code and schemas
- Adds text output capabilities alongside data output
- Simplifies error handling to return Data objects instead of raising exceptions
- Renames methods to follow component naming conventions

Key changes:
1. Changed base class from LCToolComponent to Component
2. Added text output capability through fetch_content_text method
3. Modified Data objects to include required text field for message formatting
4. Simplified error handling to match component pattern
5. Removed TavilySearchSchema and build_tool functionality

This change makes the component more consistent with other similar components in the codebase while maintaining the same core search functionality.

2024-12-24 22:59 UTC, ogabrielluiz commented
@Cristhianzl this will probably break front end tests

2025-01-13 22:45 UTC, edwinjosechittilappilly requested changes
Adhere to migration and depreciation guidelines. Also, utilize the new testing base classes along with the general tests boilerplate template.

Also you would need to update relevant tests and starter templates thats uses this component.

2025-01-17 14:55 UTC, edwinjosechittilappilly approved these changes
LGTM

2025-01-17 14:55 UTC, edwinjosechittilappilly commented
Good Work!

2025-01-17 21:26 UTC, merged