refactor(yahoo-finance): Refactor Yahoo Finance API component
langflow-ai/langflow pull request #5434
Opened 2024-12-24 23:40 UTC by raphaelchristi

This pull request refactors the Yahoo Finance API component to match the Wikidata and Wikipedia API components. It removes the dependency on LCToolComponent, adds tool_mode=True to the inputs, and adds data and text outputs

2025-01-07 11:02 UTC, cbornet commented on src/backend/base/langflow/components/tools/yahoo_finance.py
> +class YfinanceToolComponent(Component):
Is it not a breaking change ?

2025-01-07 21:59 UTC, raphaelchristi commented on src/backend/base/langflow/components/tools/yahoo_finance.py
> +class YfinanceToolComponent(Component):
Thanks for the review! Regarding the breaking change - you're right, but the LCToolComponent is no longer needed since we're now using tool_mode directly.

2025-01-13 22:45 UTC, edwinjosechittilappilly requested changes
Adhere to migration and depreciation guidelines. Also, utilize the new testing base classes along with the general tests boilerplate template.

Also you would need to update relevant tests and starter templates thats uses this component.

2025-01-14 13:54 UTC, cbornet commented
@raphaelchristi would it be possible instead to modify `LCToolComponent` to add `tool_mode` to it ?

2025-01-17 17:48 UTC, edwinjosechittilappilly approved these changes
LGTM

2025-01-17 17:48 UTC, edwinjosechittilappilly commented on src/backend/base/langflow/components/tools/yahoo.py
> +
name="Yahoo Finance"

2025-01-17 23:55 UTC, edwinjosechittilappilly commented
@raphaelchristi  Please revert back changes in old test file of yahoo finance.
If possible create a new test class for the new component.

2025-01-20 07:09 UTC, edwinjosechittilappilly approved these changes
LGTM

2025-01-20 15:29 UTC, merged