refactor(google_search): migrate to new tool mode implementation
langflow-ai/langflow pull request #5444
Opened 2024-12-25 20:46 UTC by Vigtu

- Replace legacy tool mode using LCToolComponent with new Component class and tool_mode flag.

- Update input/output definitions to use new DataFrame type and explicit Output configuration.

Key changes:
- Migrate from LCToolComponent to Component base class
- Add explicit output configuration with DataFrame type
- Update error handling to return structured DataFrame responses
- Implement tool_mode using new flag syntax

![image](https://github.com/user-attachments/assets/77cbde0b-f085-4386-996a-d6715d9c7b87)
![image](https://github.com/user-attachments/assets/c616eaa1-f0af-4c17-b770-af826a304c26)

2024-12-30 12:09 UTC, Vigtu commented
@carlosrcoelho

2025-01-13 22:42 UTC, edwinjosechittilappilly requested changes
Adhere to migration and depreciation guidelines. Also, utilize the new testing base classes along with the general tests boilerplate template.

2025-01-15 13:45 UTC, Vigtu commented
> Adhere to migration and depreciation guidelines. Also, utilize the new testing base classes along with the general tests boilerplate template.

I will work on this!

2025-01-17 19:03 UTC, edwinjosechittilappilly approved these changes
code LGTM

2025-01-18 00:26 UTC, merged