refactor(google_serper_api): migrate to new tool mode implementation
langflow-ai/langflow pull request #5446
Opened 2024-12-25 21:08 UTC by Vigtu

Replace legacy LCToolComponent implementation with new Component base class

- Migrate from LCToolComponent to Component base class
- Add tool_mode flag to MultilineInput
- Update output configuration to use DataFrame type
- Implement structured error handling with DataFrame responses
- Remove legacy tool mode implementation

![image](https://github.com/user-attachments/assets/13d37c6b-b01f-4195-b1c5-423cebc01083)
![image](https://github.com/user-attachments/assets/0a91df41-5ebe-40c8-88a5-835a713aea71)
![image](https://github.com/user-attachments/assets/cdea9a13-dfe4-4c73-bee5-c53230c11a8a)

2024-12-30 12:08 UTC, Vigtu commented
@carlosrcoelho

2025-01-13 22:41 UTC, edwinjosechittilappilly requested changes
Follow Migration / depreciation guidelines.

2025-01-15 13:45 UTC, Vigtu commented
> Follow Migration / depreciation guidelines.

Working on this

2025-01-17 20:48 UTC, edwinjosechittilappilly commented
if possible for the new component can you get the logo of serper?

2025-01-17 21:09 UTC, Vigtu commented
> if possible for the new component can you get the logo of serper?

Yes, I'm working on this right now...

2025-01-17 23:29 UTC, edwinjosechittilappilly approved these changes
LGTM

2025-01-18 01:21 UTC, edwinjosechittilappilly commented
Test updated!

2025-01-18 01:36 UTC, merged