feat: add GitExtractor component
langflow-ai/langflow pull request #5459
Opened 2024-12-26 17:59 UTC by raphaelchristi

This pull request introduces the GitExtractor component for analyzing Git repositories. Key features:

- Repository Info: Extracts branch, remotes, and commit details
- Statistics: Calculates file counts, sizes, and line numbers
- Directory Structure: Generates complete folder tree
- File Content: Extracts text files with binary handling
- Memory Safe: Implements content truncation for large repos
- Error Handling: Graceful error recovery and resource cleanup

2024-12-27 23:56 UTC, ogabrielluiz requested changes
Hey, @raphaelchristi 

This is looking good. 


The tmpdir calls are blocking and it would be better if they were async. Could you refactor that?

Also, you don't need to delete the folder because you could use a context manager that will remove the folder once the code block runs.

2024-12-28 04:19 UTC, raphaelchristi commented
Hi @ogabrielluiz ,

Thank you for the review! I've implemented the suggested changes:
- Converted all methods to async using async/await
- Added asynccontextmanager for the tmpdir operations
- Implemented automatic cleanup using the context manager

Let me know if you'd like me to make any additional adjustments to the implementation.

2025-01-16 18:04 UTC, edwinjosechittilappilly approved these changes
LGTM

2025-01-16 18:06 UTC, edwinjosechittilappilly commented
Good Work! @raphaelchristi  Please follow up if the tests in CI Fails!

2025-01-16 18:25 UTC, ogabrielluiz approved these changes

2025-01-17 19:33 UTC, merged