refactor(tools): overhaul Python REPL component with modern tool mode
langflow-ai/langflow pull request #5463
Opened 2024-12-26 23:39 UTC by Vigtu

BREAKING CHANGE: Complete redesign of PythonREPL component architecture

- Replace legacy tool mode with modern tool_mode=true implementation
- Add automatic import detection for both global and from-imports
- Remove manual global_imports field in favor of automatic detection
- Implement CodeInput type support with FieldTypes.CODE
- Update schema to handle new parameters for agent compatibility
- Improve error handling and logging for import failures

The component now automatically handles imports without manual configuration, supports modern tool mode, and provides better integration with the agent system through updated schema definitions.

[Python REPL Overhaul.json](https://github.com/user-attachments/files/18256114/Python.REPL.Overhaul.json)
![image](https://github.com/user-attachments/assets/ee2f76e3-287b-4428-b3e8-ec5ccef2f891)
![image](https://github.com/user-attachments/assets/357a9909-92bf-407b-b948-9766df1a7d6a)

code used on the example:

```
import random
from datetime import datetime, timedelta
from typing import List, Dict

def generate_dates(quantity: int) -> List[Dict[str, str]]:
    dates = []
    base_date = datetime.now()
    
    for i in range(quantity):
        # Add random days to base date
        days = random.randint(1, 365)
        new_date = base_date + timedelta(days=days)
        
        dates.append({
            "date": new_date.strftime("%d/%m/%Y"),
            "weekday": new_date.strftime("%A")
        })
    
    return dates

# Usage example
generated_dates = generate_dates(3)
for date in generated_dates:
    print(f"Date: {date['date']}, Day: {date['weekday']}")
  ```
    
  Or just run the code without the Agent:
  
![image](https://github.com/user-attachments/assets/e19398df-c83f-40cb-917f-ee9074eabec5)

CodeInput terminal:
![image](https://github.com/user-attachments/assets/6a3148b8-340e-49ba-8f63-0b3f5c752524)

the output:
![image](https://github.com/user-attachments/assets/3dc9467f-6bef-40f1-a238-1e351c99a9bd)

2024-12-26 23:41 UTC, Vigtu commented
@ogabrielluiz @edwinjosechittilappilly

2024-12-27 19:22 UTC, ogabrielluiz requested changes
Looking good, @Vigtu ! 

Thank you

2024-12-27 19:22 UTC, ogabrielluiz commented on src/backend/base/langflow/components/tools/python_repl.py
> +    name = "PythonREPL"
Name is not required
```suggestion
```

2024-12-27 19:22 UTC, ogabrielluiz commented on src/backend/base/langflow/components/tools/python_repl.py
> -        ),
We had imports for security reasons. We need a way to limit what the LLM can do.

2025-01-16 18:53 UTC, ogabrielluiz requested changes

2025-01-16 18:53 UTC, ogabrielluiz commented on src/backend/base/langflow/components/tools/python_repl.py
> +            info="The Python code to execute. Only modules specified in Global Imports can be used.",
You might need to tell the Agent to print the results or something like that otherwise the output won't be returned to it as you can see in the image. 
![CleanShot 2025-01-16 at 15 52 50@2x](https://github.com/user-attachments/assets/8755cfb2-7d3d-4d94-b2e7-35db5276b0a6)

2025-01-18 01:28 UTC, edwinjosechittilappilly approved these changes
LGTM

2025-01-18 08:17 UTC, Vigtu commented on src/backend/base/langflow/components/tools/python_repl.py
> +    name = "PythonREPL"
Done!

2025-01-18 17:57 UTC, edwinjosechittilappilly approved these changes
LGTM

2025-01-20 11:54 UTC, ogabrielluiz approved these changes

2025-01-20 12:07 UTC, merged