fix: the database url is missing ":\\" when sqlite or postgresql is not used
langflow-ai/langflow pull request #5492
Opened 2024-12-31 03:40 UTC by qq745639151

If I set the environment varialbe ```LANGFLOW_DATABASE_URL``` start with "mysql+aiomysql://"， the function ```_create_engine``` split it to judge the database will be used. But if sqlite or postgresql is not used. the url is missing "://"

2025-01-02 12:43 UTC, ogabrielluiz requested changes
Hey @qq745639151 

Good catch. Please take a look at my comment.

2025-01-02 12:43 UTC, ogabrielluiz commented on src/backend/base/langflow/services/database/service.py
What about something like this: 
```python

    def _create_engine(self) -> AsyncEngine:
        """Create the engine for the database."""
        url_components = self.database_url.split("://", maxsplit=1)
        if url_components[0].startswith("sqlite"):
            scheme = "sqlite+aiosqlite"
            kwargs = {}
        else:
            kwargs = {
                "pool_size": self.settings_service.settings.pool_size,
                "max_overflow": self.settings_service.settings.max_overflow,
            }
            scheme = "postgresql+psycopg" if url_components[0].startswith("postgresql") else url_components[0]
        database_url = f"{scheme}://{url_components[1]}"
        return create_async_engine(
            database_url,
            connect_args=self._get_connect_args(),
            **kwargs,
        )
 ```

2025-01-10 02:35 UTC, qq745639151 commented on src/backend/base/langflow/services/database/service.py
Good job! Your code is better than mine. it is easier to understand.

2025-01-10 11:40 UTC, ogabrielluiz approved these changes
LGTM

2025-01-10 11:56 UTC, merged