docs: API examples
langflow-ai/langflow pull request #5499
Opened 2024-12-31 17:30 UTC by mendonk

This pull request includes updates to the documentation and the OpenAPI specification for the Langflow API.

The new API Examples page includes examples for endpoints related to flow building, CRUD, file upload and download, and monitoring. Endpoints not included are documented in the swagger spec.

The OpenAPI spec has been updated to 1.1.1.

2025-01-03 17:25 UTC, anovazzi1 requested changes
- the endpoints are not working out of the box on macbook warp terminal because of the simple quotes in the url

- create multiple flows example have only one flow inside the array

- upload flow from file works fine but when passing a folder the global varaible used was not mentioned before and it does not especify how to get the folder id from the langflow ui, also if we pass a wrong id it still works but the flow can't be seen in the ui, this should be fixed but would be good to alert the user that the folder id should already exist before uploading the flow.

- download all flows endpoint uses an array of ids in it's body, but it's not clear to the user if those ids are flow ids or folder ids or if they are necessary if the endpoint should download all flows or just the ones related to the ids provided in the request.

- monitor description is not accurate, monitor endpoint does not only handle messages 

- get messages endpoint uses an optional parameter as session_id with a uuid that is not needed and can lead to confusion

- the json on this example is invalid because of the ending comma http://localhost:3000/api-reference-api-examples#update-message

- Create folder endpoint example could create a new folder without flows or component so the example can work out of the box from copy and pasting

- Update folder description does not explain exactly what the endpoint do, if we send two flow ids the folder will have the past flows + the two new ones or we will override the folder content? 

- Upload file endpoint uses a flow id, but it's not clear to the user the provided uuid need to be from an existing flow 
- would be nice to tell how to enable logs stream before this example:
<img width="420" alt="image" src="https://github.com/user-attachments/assets/a37cfd45-9aa8-479e-ac57-27713cf2cb9b" />

- simplified run flow could use the global variable for langflow_id

- run advanced could say what are the advanced options before the example

-starter-projects did not return the list of projects ad it's probably deprecated, the active endpoint is basic examples
<img width="483" alt="image" src="https://github.com/user-attachments/assets/33eb38b3-9c70-4144-84fd-53021d53822e" />

2025-01-09 15:18 UTC, anovazzi1 approved these changes
in the folder creation part I believe it would be nice to add that adding a flow to a folder moves the flow from one folder to another
<img width="985" alt="image" src="https://github.com/user-attachments/assets/cad950f2-73e0-4dab-847e-a226d6c55cb9" />

2025-01-09 19:27 UTC, anovazzi1 reviewed
waiting on /build endpoint

2025-01-09 21:46 UTC, mendonk commented
@anovazzi1 
* [Build endpoint](https://github.com/langflow-ai/langflow/pull/5499/files#diff-6b419cbbea6e751a89a918b56052505eaf4239faa2770b84b06f97e6175c8a1bR84)
* Addressed create folder

2025-01-13 14:31 UTC, anovazzi1 requested changes
almost perfect, I believe we need more info about the build endpoint, it's a really important endpoint for users that want to implement the streaming functionality.

there are other optional parameters that can be used in the body, see the image bellow:
<img width="515" alt="image" src="https://github.com/user-attachments/assets/890365a7-9947-477c-be76-60a8dda3defd" />

also say that the response of the endpoint is streaming by default so this endpoint return multiple events until the last one closes it's connection, I don't believe we need to document each event type in the example docs, but it would be nice to inform this behavior on it

2025-01-13 21:51 UTC, mendonk commented
@anovazzi1 I rewrote [the build example](https://github.com/langflow-ai/langflow/pull/5499/files#diff-6b419cbbea6e751a89a918b56052505eaf4239faa2770b84b06f97e6175c8a1bR84) to stream a token response with a chat message, instead of just posting a blank message for a single response.

2025-01-14 14:56 UTC, anovazzi1 approved these changes
lgtm

2025-01-15 14:47 UTC, KimberlyFields approved these changes
Left some style-related suggestions, but approving.

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +1. Export your Langflow URL in your terminal.
Do these items need to be completed in sequential order? If not, use a bulleted list.

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Create Flow
```suggestion
### Create flow
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Read Flows
```suggestion
### Read flows
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Read Flow
```suggestion
### Read flow
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Delete Flow
```suggestion
### Delete flow
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Get Vertex Builds
```suggestion
### Get Vertex builds
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +Retrieve Vertex Builds for a specific flow.
```suggestion
Retrieve Vertex builds for a specific flow.
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Delete Vertex Builds
```suggestion
### Delete Vertex builds
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +Delete Vertex Builds for a specific flow.
```suggestion
Delete Vertex builds for a specific flow.
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Get Messages
```suggestion
### Get messages
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Delete Messages
```suggestion
### Delete messages
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Get Transactions
```suggestion
### Get transactions
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Create Folder
```suggestion
### Create folder
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +Adding a flow to a folder will move the flow from its previous location, not copy it.
```suggestion
Adding a flow to a folder moves the flow from its previous location. The flow is not copied.
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Read Folder
```suggestion
### Read folder
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Update Folder
```suggestion
### Update folder
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +Each PATCH request will update the folder with the values you send.
```suggestion
Each PATCH request updates the folder with the values you send.
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Delete Folder
```suggestion
### Delete folder
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Download Folder
```suggestion
### Download folder
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Upload Folder
```suggestion
### Upload folder
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Upload File
```suggestion
### Upload file
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### List Files
```suggestion
### List files
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Download File
```suggestion
### Download file
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Download Image
```suggestion
### Download image
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Delete File
```suggestion
### Delete file
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +This endpoint requires that log retrieval be enabled in your Langflow application.
```suggestion
This endpoint requires log retrieval to be enabled in your Langflow application.
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Stream Logs
```suggestion
### Stream logs
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Logs
On line 1294, you have a level 2 heading called "Logs". I realize this one is a level 3 and has different information than the other heading, but it looks like it's a mistake. Can you name this one something else? Maybe "Logs with optional parameters"?

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Run Flow
```suggestion
### Run flow
```

2025-01-15 14:47 UTC, KimberlyFields commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Webhook Run Flow
```suggestion
### Webhook run flow
```

2025-01-15 16:48 UTC, mendonk commented on docs/docs/API-Reference/api-reference-api-examples.md
> +     ...
I missed the closing brackets, fixed

2025-01-15 17:02 UTC, mendonk commented on docs/docs/API-Reference/api-reference-api-examples.md
> +### Logs
Good call. Updated with more information on the parameters.

2025-01-15 17:20 UTC, merged